### ISSUE TITLE
Handle more keypresses internally?

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/neat-input#2]
Since `cabal` uses this quite heavily and I also want to use it for another chat application it would be really useful if `neat-input` could handle more things internally, related to editing the command line and would remove a lot of effort from users of `neat-input` since they wouldn't need to implement this themselves.

For example:

- [x] `ctrl-u` to erase the complete line (implemented in `cabal`)
- [x] `ctrl-a` to move the cursor to the beginning of the line
- [x] `ctrl-e` to move the cursor to the end of the line
- [x] `ctrl-b` to move the cursor to the left
- [x] `ctrl-f` to move the cursor to the right
- [x] `ctrl-k` to delete all to the right of the cursor
- [x] `ctrl-w` or `alt-backspace` to erase the word to the left of the cursor (implemented in `cabal`)
- [x] `alt-d` delete word to the right of the cursor
- [x] `alt-b` to move the cursor one word to the left
- [x] `alt-f` to move the cursor one word to the right

These are the ones I can come up with on the top of my head, but I'm sure there are more.

This could also be an opt-in thing, so you could still disable it if you wanted to. But it would be really nice if it was a more "fully featured" input component.

WDYT?

cc @noffle

**Comment by mafintosh** [comment]
I'd be fine with this. Open a PR if you frel like it :)

**Comment by cblgh** [comment]
+1!

**Comment by hackergrrl** [comment]
This could be a cool thing to consolidate into a `libreadline`-like module.
